<a href="https://colab.research.google.com/github/valentingracia/codingDojoDC/blob/main/practicaCambioNombreColumna.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Alumno: Valentin Gracia
**Data Science Coding Dojo G1**

Montamos el drive junto con el dataframe

In [27]:
from google.colab import drive
#drive.mount('/content/drive')

import pandas as pd

filename = '/content/drive/MyDrive/Coding Dojo/Semana2/RailsToTrails_National_Count_Data_week.xlsx'
bike_df = pd.read_excel(filename)
print(bike_df.head())
print(bike_df.columns)
#bike_df.info

  Timeframe    Week of  ...  Unnamed: 8  Unnamed: 9
0    Week 1 2020-12-30  ...         NaN         NaN
1    Week 2 2020-01-06  ...         NaN         NaN
2    Week 3 2020-01-13  ...         NaN         NaN
3    Week 4 2020-01-20  ...         NaN         NaN
4    Week 5 2020-01-27  ...         NaN         NaN

[5 rows x 10 columns]
Index(['Timeframe', 'Week of', ' 2019 counts (31 counters)',
       ' 2020 counts (31 counters)', '2021 Counts', 'Change 2019-2020',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [28]:
bike_df.rename(columns={"Unnamed: 6":"percent_change"})

   Timeframe    Week of  ...  Unnamed: 8  Unnamed: 9
0     Week 1 2020-12-30  ...         NaN         NaN
1     Week 2 2020-01-06  ...         NaN         NaN
2     Week 3 2020-01-13  ...         NaN         NaN
3     Week 4 2020-01-20  ...         NaN         NaN
4     Week 5 2020-01-27  ...         NaN         NaN
5     Week 6 2020-02-03  ...         NaN         NaN
6     Week 7 2020-02-10  ...         NaN         NaN
7     Week 8 2020-02-17  ...         NaN         NaN
8     Week 9 2020-02-24  ...         NaN         NaN
9    Week 10 2020-03-02  ...         NaN         NaN
10   Week 11 2020-03-09  ...         NaN         NaN
11   Week 12 2020-03-16  ...         NaN         NaN
12   Week 13 2020-03-23  ...         NaN         NaN
13   Week 14 2020-03-30  ...         NaN         NaN
14   Week 15 2020-04-06  ...         NaN         NaN
15   Week 16 2020-04-13  ...         NaN         NaN
16   Week 17 2020-04-20  ...         NaN         NaN
17   Week 18 2020-04-27  ...         NaN         NaN
18   Week 19 2020-05-04  ...         NaN         NaN
19   Week 20 2020-05-11  ...         NaN         NaN
20   Week 21 2020-05-18  ...         NaN         NaN
21   Week 22 2020-05-25  ...         NaN         NaN
22   Week 23 2020-06-01  ...         NaN         NaN
23   Week 24 2020-06-08  ...         NaN         NaN
24   Week 25 2020-06-15  ...         NaN         NaN
25   Week 26 2020-06-22  ...         NaN         NaN
26   Week 27 2020-06-29  ...         NaN         NaN
27   Week 28 2020-07-06  ...         NaN         NaN
28   Week 29 2020-07-13  ...         NaN         NaN
29   Week 30 2020-07-20  ...         NaN         NaN
30   Week 31 2020-07-27  ...         NaN         NaN
31   Week 32 2020-08-03  ...         NaN         NaN
32   Week 33 2020-08-10  ...         NaN         NaN
33   Week 34 2020-08-17  ...         NaN         NaN
34   Week 35 2020-08-24  ...         NaN         NaN
35   Week 36 2020-08-31  ...         NaN         NaN
36   Week 37 2020-09-07  ...         NaN         NaN
37   Week 38 2020-09-14  ...         NaN         NaN
38   Week 39 2020-09-21  ...         NaN         NaN
39   Week 40 2020-09-28  ...         NaN         NaN
40   Week 41 2020-10-05  ...         NaN         NaN
41   Week 42 2020-10-12  ...         NaN         NaN
42   Week 43 2020-10-19  ...         NaN         NaN
43   Week 44 2020-10-26  ...         NaN         NaN
44   Week 45 2020-11-02  ...         NaN         NaN
45   Week 46 2020-11-09  ...         NaN         NaN
46   Week 47 2020-11-16  ...         NaN         NaN
47   Week 48 2020-11-23  ...         NaN         NaN
48   Week 49 2020-11-30  ...         NaN         NaN
49   Week 50 2020-12-07  ...         NaN         NaN
50   Week 51 2020-12-14  ...         NaN         NaN
51   Week 52 2020-12-21  ...   26.728808    0.514016

[52 rows x 10 columns]

Reporte Nan

In [29]:
bike_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timeframe                   52 non-null     object
 1   Week of                     52 non-null     datetime64[ns]
 2    2019 counts (31 counters)  52 non-null     int64
 3    2020 counts (31 counters)  52 non-null     int64
 4   2021 Counts                 0 non-null      float64
 5   Change 2019-2020            52 non-null     float64
 6   Unnamed: 6                  52 non-null     float64
 7   Unnamed: 7                  0 non-null      float64
 8   Unnamed: 8                  1 non-null      float64
 9   Unnamed: 9                  1 non-null      float64
dtypes: datetime64[ns](1), float64(6), int64(2), object(1)
memory usage: 4.2+ KB

Llenar 2021 Count con "0"

In [30]:
#bike_df=bike_df.loc[:, '2021 Counts'].fillna(0)
bike_df['2021 Counts'].fillna(0,inplace=True)
bike_df

   Timeframe    Week of  ...  Unnamed: 8  Unnamed: 9
0     Week 1 2020-12-30  ...         NaN         NaN
1     Week 2 2020-01-06  ...         NaN         NaN
2     Week 3 2020-01-13  ...         NaN         NaN
3     Week 4 2020-01-20  ...         NaN         NaN
4     Week 5 2020-01-27  ...         NaN         NaN
5     Week 6 2020-02-03  ...         NaN         NaN
6     Week 7 2020-02-10  ...         NaN         NaN
7     Week 8 2020-02-17  ...         NaN         NaN
8     Week 9 2020-02-24  ...         NaN         NaN
9    Week 10 2020-03-02  ...         NaN         NaN
10   Week 11 2020-03-09  ...         NaN         NaN
11   Week 12 2020-03-16  ...         NaN         NaN
12   Week 13 2020-03-23  ...         NaN         NaN
13   Week 14 2020-03-30  ...         NaN         NaN
14   Week 15 2020-04-06  ...         NaN         NaN
15   Week 16 2020-04-13  ...         NaN         NaN
16   Week 17 2020-04-20  ...         NaN         NaN
17   Week 18 2020-04-27  ...         NaN         NaN
18   Week 19 2020-05-04  ...         NaN         NaN
19   Week 20 2020-05-11  ...         NaN         NaN
20   Week 21 2020-05-18  ...         NaN         NaN
21   Week 22 2020-05-25  ...         NaN         NaN
22   Week 23 2020-06-01  ...         NaN         NaN
23   Week 24 2020-06-08  ...         NaN         NaN
24   Week 25 2020-06-15  ...         NaN         NaN
25   Week 26 2020-06-22  ...         NaN         NaN
26   Week 27 2020-06-29  ...         NaN         NaN
27   Week 28 2020-07-06  ...         NaN         NaN
28   Week 29 2020-07-13  ...         NaN         NaN
29   Week 30 2020-07-20  ...         NaN         NaN
30   Week 31 2020-07-27  ...         NaN         NaN
31   Week 32 2020-08-03  ...         NaN         NaN
32   Week 33 2020-08-10  ...         NaN         NaN
33   Week 34 2020-08-17  ...         NaN         NaN
34   Week 35 2020-08-24  ...         NaN         NaN
35   Week 36 2020-08-31  ...         NaN         NaN
36   Week 37 2020-09-07  ...         NaN         NaN
37   Week 38 2020-09-14  ...         NaN         NaN
38   Week 39 2020-09-21  ...         NaN         NaN
39   Week 40 2020-09-28  ...         NaN         NaN
40   Week 41 2020-10-05  ...         NaN         NaN
41   Week 42 2020-10-12  ...         NaN         NaN
42   Week 43 2020-10-19  ...         NaN         NaN
43   Week 44 2020-10-26  ...         NaN         NaN
44   Week 45 2020-11-02  ...         NaN         NaN
45   Week 46 2020-11-09  ...         NaN         NaN
46   Week 47 2020-11-16  ...         NaN         NaN
47   Week 48 2020-11-23  ...         NaN         NaN
48   Week 49 2020-11-30  ...         NaN         NaN
49   Week 50 2020-12-07  ...         NaN         NaN
50   Week 51 2020-12-14  ...         NaN         NaN
51   Week 52 2020-12-21  ...   26.728808    0.514016

[52 rows x 10 columns]

cambiar nombre columna " 2019 counts (31 counters)"

In [31]:
bike_df.rename(columns={" 2019 counts (31 counters)":"conteos_2019"})

   Timeframe    Week of  conteos_2019  ...  Unnamed: 7  Unnamed: 8  Unnamed: 9
0     Week 1 2020-12-30        167679  ...         NaN         NaN         NaN
1     Week 2 2020-01-06         82340  ...         NaN         NaN         NaN
2     Week 3 2020-01-13         62315  ...         NaN         NaN         NaN
3     Week 4 2020-01-20         75801  ...         NaN         NaN         NaN
4     Week 5 2020-01-27         75841  ...         NaN         NaN         NaN
5     Week 6 2020-02-03         79780  ...         NaN         NaN         NaN
6     Week 7 2020-02-10         65732  ...         NaN         NaN         NaN
7     Week 8 2020-02-17         69492  ...         NaN         NaN         NaN
8     Week 9 2020-02-24         85688  ...         NaN         NaN         NaN
9    Week 10 2020-03-02         84512  ...         NaN         NaN         NaN
10   Week 11 2020-03-09        107995  ...         NaN         NaN         NaN
11   Week 12 2020-03-16        125440  ...         NaN         NaN         NaN
12   Week 13 2020-03-23        136330  ...         NaN         NaN         NaN
13   Week 14 2020-03-30        118784  ...         NaN         NaN         NaN
14   Week 15 2020-04-06        132033  ...         NaN         NaN         NaN
15   Week 16 2020-04-13        133267  ...         NaN         NaN         NaN
16   Week 17 2020-04-20        165777  ...         NaN         NaN         NaN
17   Week 18 2020-04-27        166356  ...         NaN         NaN         NaN
18   Week 19 2020-05-04        171049  ...         NaN         NaN         NaN
19   Week 20 2020-05-11        178534  ...         NaN         NaN         NaN
20   Week 21 2020-05-18        191319  ...         NaN         NaN         NaN
21   Week 22 2020-05-25        240507  ...         NaN         NaN         NaN
22   Week 23 2020-06-01        211380  ...         NaN         NaN         NaN
23   Week 24 2020-06-08        214729  ...         NaN         NaN         NaN
24   Week 25 2020-06-15        202847  ...         NaN         NaN         NaN
25   Week 26 2020-06-22        202445  ...         NaN         NaN         NaN
26   Week 27 2020-06-29        184658  ...         NaN         NaN         NaN
27   Week 28 2020-07-06        185302  ...         NaN         NaN         NaN
28   Week 29 2020-07-13        166125  ...         NaN         NaN         NaN
29   Week 30 2020-07-20        208809  ...         NaN         NaN         NaN
30   Week 31 2020-07-27        197005  ...         NaN         NaN         NaN
31   Week 32 2020-08-03        180605  ...         NaN         NaN         NaN
32   Week 33 2020-08-10        191450  ...         NaN         NaN         NaN
33   Week 34 2020-08-17        168754  ...         NaN         NaN         NaN
34   Week 35 2020-08-24        176624  ...         NaN         NaN         NaN
35   Week 36 2020-08-31        184806  ...         NaN         NaN         NaN
36   Week 37 2020-09-07        157345  ...         NaN         NaN         NaN
37   Week 38 2020-09-14        152527  ...         NaN         NaN         NaN
38   Week 39 2020-09-21        141072  ...         NaN         NaN         NaN
39   Week 40 2020-09-28        135881  ...         NaN         NaN         NaN
40   Week 41 2020-10-05        132239  ...         NaN         NaN         NaN
41   Week 42 2020-10-12        110816  ...         NaN         NaN         NaN
42   Week 43 2020-10-19        110761  ...         NaN         NaN         NaN
43   Week 44 2020-10-26        109795  ...         NaN         NaN         NaN
44   Week 45 2020-11-02        109766  ...         NaN         NaN         NaN
45   Week 46 2020-11-09         86824  ...         NaN         NaN         NaN
46   Week 47 2020-11-16         88122  ...         NaN         NaN         NaN
47   Week 48 2020-11-23         72380  ...         NaN         NaN         NaN
48   Week 49 2020-11-30         81871  ...         NaN         NaN         NaN
49   Week 50 2020-12-07         68364  ...         NaN         NaN         NaN
50   Week 51 2020-12-14         58063  ...         NaN         NaN         NaN
51   Week 52 2020-12-21         71890  ...         NaN   26.728808    0.514016

[52 rows x 10 columns]